export const Questions = [
    {
        id: 1,
        img: "https://cdn.pixabay.com/photo/2020/05/12/15/43/antarctica-5163636_1280.jpg",
        prompt: "Vad är orsaken till de stigande havsnivåerna?",
        optionA: "Den globala uppvärmningen",
        optionB: "Alla badar i havet samtidigt",
        optionC: "Mer skräp slängs i havet",
        optionD: "Det regnar mer än vanligt",
        answer: "A",
        correct: "Helt rätt! Det gör att is och snö på Grönland och i Antarktis smälter snabbare, vilket gör att det blir mer vatten i havet.",
        wrong: "Nej, den globala uppvärmningen är orsaken.",
    },
    {
        id: 2,
        img: "https://cdn.pixabay.com/photo/2019/06/23/20/19/power-plant-4294655_1280.jpg",
        prompt: "Vad är den största orsaken till ökade halter växthusgaser?",
        optionA: "Översvämningar",
        optionB: "Brist på färskvatten",
        optionC: "Flera bygger växthus",
        optionD: "Förbränning av fossila bränslen",
        answer: "D",
        correct: "Rätt! Fossila bränslen, till exempel stenkol, är det som återstår av forntida växter och djur som legat begravda djupt nere i marken i flera miljoner år och omvandlats till ämnen som kan användas som bränsle.",
        wrong: "Nej, förbränning av fossila bränseln är den största orsaken.",
    },
    {
        id: 3,
        img: "https://cdn.pixabay.com/photo/2019/01/11/11/25/greenland-3926927_1280.jpg",
        prompt: "Vilket stort rovdjur är helt beroende av havsisen i Arktis?",
        optionA: "Snöleoparden",
        optionB: "Valrossen",
        optionC: "Isbjörnen",
        optionD: "Snömannen",
        answer: "C",
        correct: "Du har rätt! På grund av klimatförändringarna är den en utrotningshotad art.",
        wrong: "Inte riktigt, rätt svar är isbjörnen!",
    },
]